version: "3.8"

volumes:
  esdata01:
    driver: local

networks:
  default:
    name: elastic
    external: false

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION} # Elasticsearch 이미지 사용
    labels:
      co.elastic.logs/module: elasticsearch # 로그 모듈로 elasticsearch 사용
    volumes:
      - esdata01:/usr/share/elasticsearch/data # 데이터 디렉토리를 컨테이너에 마운트
    ports:
      - ${ES_PORT}:9200
    environment: # 환경 변수 설정
      - node.name=es01 # 노드 이름 설정
      - cluster.name=${CLUSTER_NAME} # 클러스터 이름 설정
      - discovery.type=single-node # 단일 노드 모드 설정
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # Elastic 사용자 비밀번호 설정
      - bootstrap.memory_lock=true # 메모리 잠금 설정
      - xpack.security.enabled=true # X-Pack 보안 활성화
      - xpack.security.http.ssl.enabled=false # HTTP SSL 비활성화
      - xpack.security.transport.ssl.enabled=false # Transport SSL 비활성화
      - xpack.license.self_generated.type=${LICENSE} # 라이선스 유형 설정
    mem_limit: ${ES_MEM_LIMIT} # 메모리 제한 설정
    ulimits: # ulimit 설정
      memlock: # 메모리 락은 무제한으로 설정
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://es01:9200
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JDBC_DRIVER_URL=${JDBC_DRIVER_URL}
      - JDBC_DRIVER_PATH=${JDBC_DRIVER_PATH}
    depends_on:
      - es01
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "if [ ! -f ${JDBC_DRIVER_PATH} ]; then
         curl -o ${JDBC_DRIVER_PATH} ${JDBC_DRIVER_URL};
       fi &&
       /usr/local/bin/docker-entrypoint"
    ports:
      - "5044:5044" # Logstash input port (optional)