metricbeat.config.modules: # Metricbeat 모듈 설정
  path: ${path.config}/modules.d/*.yml # 모듈 설정 파일의 경로
  reload.enabled: false # 설정 변경 시 자동으로 재로드하지 않음

metricbeat.modules: # Metricbeat 모듈 구성
  - module: elasticsearch # Elasticsearch 모듈 설정
    xpack.enabled: true # X-Pack 기능 활성화
    period: 10s # 주기적으로 수집할 시간 간격
    hosts: ${ELASTIC_HOSTS} # Elasticsearch 호스트
    ssl.certificate_authorities: "certs/ca/ca.crt" # SSL 인증서 권한
    ssl.certificate: "certs/es01/es01.crt" # SSL 인증서
    ssl.key: "certs/es01/es01.key" # SSL 키
    username: ${ELASTIC_USER} # Elasticsearch 사용자 이름
    password: ${ELASTIC_PASSWORD} # Elasticsearch 비밀번호
    ssl.enabled: true # SSL 활성화

  - module: logstash # Logstash 모듈 설정
    xpack.enabled: true # X-Pack 기능 활성화
    period: 10s # 주기적으로 수집할 시간 간격
    hosts: ${LOGSTASH_HOSTS} # Logstash 호스트

  - module: kibana # Kibana 모듈 설정
    metricsets:
      - stats # 수집할 메트릭 종류
    period: 10s # 주기적으로 수집할 시간 간격
    hosts: ${KIBANA_HOSTS} # Kibana 호스트
    username: ${ELASTIC_USER} # Elasticsearch 사용자 이름
    password: ${ELASTIC_PASSWORD} # Elasticsearch 비밀번호
    xpack.enabled: true # X-Pack 기능 활성화

  - module: docker # Docker 모듈 설정
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "memory"
      - "network" # 수집할 Docker 메트릭 종류
    hosts: ["unix:///var/run/docker.sock"] # Docker 호스트
    period: 10s # 주기적으로 수집할 시간 간격
    enabled: true # 모듈 활성화

processors: # 데이터 전처리 프로세서 설정
  - add_host_metadata: ~ # 호스트 메타데이터 추가
  - add_docker_metadata: ~ # Docker 메타데이터 추가

output.elasticsearch: # Elasticsearch 출력 설정
  hosts: ${ELASTIC_HOSTS} # Elasticsearch 호스트
  username: ${ELASTIC_USER} # Elasticsearch 사용자 이름
  password: ${ELASTIC_PASSWORD} # Elasticsearch 비밀번호
  ssl: # SSL 설정
    certificate: "certs/es01/es01.crt" # SSL 인증서
    certificate_authorities: "certs/ca/ca.crt" # SSL 인증서 권한
    key: "certs/es01/es01.key" # SSL 키