spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_c
        hikari:
            username: root
            password: 1234
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update

logging:
    level:
        org:
            springframework:
                jdbc:
                    core:
                        JdbcTemplate: DEBUG
                        StatementCreatorUtils: TRACE